### ISSUE TITLE
Existing string changes not flaged as "new"

### ISSUE THREAD

**Issue by TitaneBoy** [martinroob/ngx-i18nsupport#101]
Hello @martinroob . Thank you in advance for your great job about this package. I love it very much.

I was testing it in my side and the only issue (for now) I found about is that there is no support for changes on existing string.

Let say I have a string in english that tells: "Hello World" and there is already translation in my language (french) for this string.
Let see what we have in my french xlf file:

```
</trans-unit><trans-unit id="home.welcome.helloworld" datatype="html">
        <source>Hello World</source><target state="translated">Bonjour le monde</target>
        <context-group purpose="location">
          <context context-type="sourcefile">app/home/home.component.html</context>
          <context context-type="linenumber">5</context>
        </context-group>
</trans-unit>
```

If developper decide to change this string to: "Hello my pretty World"..

When executing the command to extract i18n strings 
`npm run extract-i18n`

and when xliffmerge merges the string to the other messages.xlf files (messages.fr.xlf file for example), the only difference is that the source string has changed. That's ok, but since the string is different, the target should, in my opinion, be changed to "new" in order to let the translators to translate this new string.
But actually, it didn't change anything about the state...just the source string:

```
</trans-unit><trans-unit id="home.welcome.helloworld" datatype="html">
        <source>Hello my pretty World</source><target state="translated">Bonjour le monde</target>
        <context-group purpose="location">
          <context context-type="sourcefile">app/home/home.component.html</context>
          <context context-type="linenumber">5</context>
        </context-group>
</trans-unit>
```

I think that "state" should change from "translated" to "new".

Do you think you could do anything to fix this ? What do you think about this case ?

Thank you in advance for your answer.

**Comment by martinroob** [comment]
Sorry for the late reply. Was a little bit ill last days.
Yes, this is a valid improvement.
It only can happen when you use fixed IDs, otherwise any source change would change the ID.
But in the case of fixed ID xliffmerge could check, wether the source has changed and then mark the translation as something like "needs review".
Will start working on it soon.

**Comment by martinroob** [comment]
Checked this issue ones again.
I come to the conclusion that the current behaviour is correct.
There are 3 different states a translation can have
- `new`
- `translated`
- `final`
`new` means it is not translated and you have to do it. `translated` means there is a translation but it is not finally checked. `final` means it is translated and reviewed to be ok.

When you change the source, `xliffmerge` corrects the `final` state to `translated` because you have to check the translations again. When the state is `translated` it will not change it.

So in your case your first translation state should not be `translated` but `final` .
Then xliffmerge will reset it to `translated`.

**Comment by TitaneBoy** [comment]
@martinroob Thank you for your answer. I understand your point.

I have a last question... I wonder How translators can translate easily the xliff file updated by xliffmerge.
Is there any tool that can give translators an easy way to change the state of a translation (for example, from new to final) ? I'm not sure that it is a good idea to ask translators to edit it manually in the file itself. I know that you suggested we use tiny-translator but since we must make some manipulations in order to build it and make it functional and since translators have no programming skills, I wonder if there is another tool that can help translators to change the "new" state to "final" when they have translated something.

Thank you in advance again for your answer and your support.
