### ISSUE TITLE
Format conversion support

### ISSUE THREAD

**Issue by sebek64** [martinroob/ngx-i18nsupport#30]
I'd be a really nice feature to support conversion among the supported file formats (including conversion of message ids). In fact, there is probably no simple way to migrate from xliff 1.2 to xliff 2.0 at the moment.

**Comment by martinroob** [comment]
Hello,
In fact I have already thought about a conversion mechanism.
But I was not sure whether there is a real use case for it.
The format you choose does not play a great role.
But once chosen it is difficult to change it.
What would be the scenario, why you want to change the format?

Converting  from xliff 1.2 to 2.0 is easy in principle, but difficult in real live because of the different IDs
There is an open issue about that on the Angular sight. 

Best regards Martin

**Comment by sebek64** [comment]
Thank you for the quick response.

Use case: project started with xliff 1.2, has quite a lot of translations, and wants to upgrade to a more modern format xliff 2.0 (e.g., because it is a bit more concise or for whatever reason one wants to use newer version of the standard).

If the only problem is with conversion of message ids, I guess that could be solved. If I understand it correctly, both types of auto-generated message ids can be extracted from source of the translation. I can play with it for some time and contribute this feature if you agree that it belongs to this project.

**Comment by martinroob** [comment]
The problem with the IDS is described in the Angular issue #15136
Olivier also added a link to the source that shows how the IDS are computed.
In principle it is just a function of source, meaning and description, but there seems to be some ICU magic too.
1.2 uses the digest function. 2.0 the decimal Ids. 
The ng team has some problem to fix it because it would be a breaking change.

So if you are interested in studying how the IDS are generated, it would be great.

**Comment by sebek64** [comment]
Thanks for pointing me to the Angular issue. From that, I've found a pull request https://github.com/angular/angular/pull/15621 which contains some kind of migrator. So I guess I'd be an unnecessary effort to write the conversion here too.

**Comment by martinroob** [comment]
Nice to see the migration tool coming with ng 5.
I only knew that they were planning to do that.

So I will close this issue.
