### ISSUE TITLE
Minor bugs

### ISSUE THREAD

**Issue by FallenRiteMonk** [martinroob/ngx-i18nsupport#87]
Base translation file 'messages.xls' with ```source-language="en"``` gets changed to ```source-language="de"``` if ```"defaultLanguage": "en"``` is not specified in config, even though the documentation claims that "en" is the default value.

The <trans-unit> in base file, containing <source>:
```<x id="START_TAG_STRONG" ctype="x-strong" equiv-text="&lt;strong&gt;"/>P<x id="CLOSE_TAG_STRONG" ctype="x-strong" equiv-text="&lt;/strong&gt;"/>izza```
gets changed in the translation file for "de" to:
```<x id="START_TAG_STRONG" ctype="x-strong" equiv-text="&lt;strong>"/>P<x id="CLOSE_TAG_STRONG" ctype="x-strong" equiv-text="&lt;/strong>"/>izza```
(```"&lt;/strong&gt;"``` gets changed to ```"&lt;/strong>"```)
This results in an error if the application is served in german

Otherwise great tool, thanks!

**Comment by martinroob** [comment]
Sorry, the documentation is wrong here.
The default language is not English, but the first language in the list of languages `languages, if you do not specify it explicitly via `defaultLanguage`.

The `"&lt;/strong>"`instead of `"&lt;/strong&gt;"` should not lead to an error, because it is both equivalent. You do not need to use `&gt;` in attribute values.

**Comment by FallenRiteMonk** [comment]
Okey.

I'll reproduce the error tomorrow and send you the exact report.

Still I think this should not happen,or at least only if "beautifyOutput" is set to true.

**Comment by FallenRiteMonk** [comment]
I was not able to reproduce the error, so I guess there was something else wrong. You were wright.

Still I think this change should only happen if "beautifyOutput" is set to true.
