### ISSUE TITLE
Preserve order

### ISSUE THREAD

**Issue by ln-e** [martinroob/ngx-i18nsupport#96]
Hello, thanks for your tool.

If I added some text later, it will be inserted at the bottom of translation file `message.fr.xlf`. However in extracted `messages.xlf` it grouped by templates. I suppose it will be much simple to maintain translations if we can preverse order, insert new untranslated nodes in the same place as it is in `messages.xlf`.

What do you think?

**Comment by martinroob** [comment]
You are right. It would be mich nice to add new units at the same position as in the original.
Will have a look at it.

**Comment by thecp** [comment]
Is there a possibility to disable this feature, maybe via config, and put new translations to the end again? We had to revert the newest version to 0.16.x. It doesn't work for us because we extract the translations to a xmb file and then merge it to different xtb files. Hence the new entries appear somewhere in the xtb files and without looking to the git there's no way to find out what has to be translated.

**Comment by martinroob** [comment]
Made a follow up issue for this (#108)
